name: Release CI
on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.9"

      - name: Set up Python
        run: uv python install

      - name: Install the project dependencies
        run: uv sync --all-extras --dev

      - name: Build executable
        run: uv run pyinstaller --onefile --windowed --add-data "im:im" --add-data "snd:snd" --name "Galaxy Wars" galaxy-wars.py

      - name: Uploading app
        uses: actions/upload-artifact@v4
        with:
          name: galaxy-wars-dist
          path: dist

  Create_Release:
    runs-on: macos-latest
    needs: [Build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Galaxy Wars
        uses: actions/download-artifact@v4
        with:
          name: galaxy-wars-dist
          path: ./dist

      - name: Generate Release Tag
        id: release_tag
        uses: amitsingh-007/next-release-tag@v6.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yy.mm.i'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.release_tag.outputs.next_release_tag }}
          tag_name: ${{ steps.release_tag.outputs.next_release_tag }}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: true
          files: |
            ./dist/*.app
